version: '3.8'

services:
  app:
    image: sciohub/innovation-catalogue-ui-ng:dev
    container_name: innovation-catalogue-ui-ng
    ports:
      - 50300:80
    networks:
      - default

networks:
  default:
    name: app