version: '3.8'

services:
  app:
    image: sciohub/innovation-catalogue-ui-ng:staging
    container_name: innovation-catalogue-ui-ng
    ports:
      - 50300:80
    volumes:
      - nginx:/etc/nginx/
      - /var/log/nginx/reverse-access.log:/var/log/nginx/reverse-access.log
      - /var/log/nginx/reverse-error.log:/var/log/nginx/reverse-error.log
      
volumes:
  nginx: