const configurationArray = [
    {
        tabHeader: 'Description Fields',
        content: [
            {
                id: "1.1",
                type: 'text',
                mandatory: true,
                minCharacters: 3,
                maxCharacters: 300,
                label: 'Title',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
            },
            {
                id: "1.2",
                type: 'text area',
                mandatory: true,
                minCharacters: 3,
                maxCharacters: 300,
                label: 'Summary',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
            },
            {
                id: "1.3",
                type: 'list',
                mandatory: true,
                minWords: 1,
                maxWords: 10,
                label: 'Business Category',
                fieldInformation: '',
                valid: false,
                options: []
            },
            {
                id: "1.4",
                type: 'list',
                mandatory: true,
                minWords: 1,
                maxWords: 10,
                label: 'Administrative Scale',
                fieldInformation: '',
                valid: false,
                options: []
            },
            {
                id: "1.5",
                type: 'chip',
                mandatory: true,
                minCharacters: 3,
                maxCharacters: 300,
                label: 'Keywords',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
            },
            {
                id: "1.6",
                type: 'text',
                mandatory: true,
                minCharacters: 3,
                maxCharacters: 300,
                label: 'Innovation URL',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
            },
            {
                id: "1.7",
                type: 'upload',
                mandatory: true,
                minCharacters: 3,
                maxCharacters: 300,
                label: 'Image of the Innovation',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
            },
            {
                id: "1.8",
                type: 'upload',
                mandatory: true,
                minCharacters: 3,
                maxCharacters: 300,
                label: 'Images of the Innovation Components',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
            },
            {
                id: "1.9",
                type: 'list',
                mandatory: true,
                minWords: 1,
                maxWords: 10,
                label: 'Technical Field',
                fieldInformation: '',
                valid: false,
                options: []
            },
            {
                id: "1.10",
                type: 'list',
                mandatory: false,
                minWords: 0,
                maxWords: 10,
                label: 'Type of Innovation (Initially Reported)',
                fieldInformation: '',
                valid: false,
                options: [],
                disabled: true
            },
            {
                id: "1.11",
                type: 'list',
                mandatory: true,
                minWords: 1,
                maxWords: 10,
                label: 'Type of Innovation',
                fieldInformation: '',
                valid: false,
                options: []
            },
            {
                id: "1.12",
                type: 'list',
                mandatory: true,
                minWords: 1,
                maxWords: 10,
                label: 'Governance Type',
                fieldInformation: '',
                valid: false,
                options: []
            },
            {
                id: "1.13",
                type: 'list',
                mandatory: true,
                minWords: 1,
                maxWords: 10,
                label: 'Related Innovations',
                fieldInformation: '',
                valid: false,
                options: []
            },
        ]
    },
]

export default configurationArray