const configurationArray = [
    {
        tabHeader: 'Benefit/Impact Fields',
        content: [
            {
                id: "2.1",
                type: 'list',
                mandatory: true,
                minWords: 1,
                maxWords: 10,
                label: 'CGIAR Action Areas',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
                resultsKeyword: 'CGIAR_impact_area'
            },
            {
                id: "2.2",
                type: 'text area',
                mandatory: true,
                minCharacters: 3,
                maxCharacters: 300,
                label: 'Value Added of the Innovation',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
            },
            {
                id: "2.3",
                type: 'text area',
                mandatory: true,
                minCharacters: 3,
                maxCharacters: 300,
                label: 'Main Advantages',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
            },
            {
                id: "2.4",
                type: 'text area',
                mandatory: true,
                minCharacters: 3,
                maxCharacters: 300,
                label: 'Main Disadvantages',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
            },
            {
                id: "2.5",
                type: 'text area',
                mandatory: true,
                minCharacters: 3,
                maxCharacters: 300,
                label: 'Description of the problem the innovation provides a solution',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
            },
            {
                id: "2.6",
                type: 'acordion',
                mandatory: true,
                minCharacters: 3,
                maxCharacters: 300,
                label: 'SDG Target Addressed',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
            },
            {
                id: "2.7",
                type: 'acordion',
                mandatory: true,
                minCharacters: 3,
                maxCharacters: 300,
                label: 'CGIAR Impact Target',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
            },
            {
                id: "2.8",
                type: 'text area',
                mandatory: true,
                minCharacters: 3,
                maxCharacters: 300,
                label: 'Initiative/Project Outcome Addressed',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
            },
            {
                id: "2.9",
                type: 'list',
                mandatory: true,
                minWords: 1,
                maxWords: 10,
                label: 'Environmental Benefits',
                fieldInformation: 'Max 300 characters including spaces',
                valid: false,
                resultsKeyword: 'Environmental_benefits'
            },
        ]
    },
]

export default configurationArray