export const Actions = {
    SetCurrentPage: "SetCurrentPage",
    SetLoggedIn: "SetLoggedIn",
    SetCsrfToken: "SetCsrfToken",
    SetAccessToken: "SetAccessToken",
    SetUserData: "SetUserData",
    SetStep: "SetStep",
    SetResults: "SetResults",
    SetAccordionData: "SetAccordionData",
    SetDescriptionValues: "SetDescriptionValues",
    SetBenefitImpactValues: "SetBenefitImpactValues",
    SetContextValues: "SetContextValues",
    SetEvidenceValues: "SetEvidenceValues",
    SetIntellectualPropertyValues: "SetIntellectualPropertyValues",
    SetInterventionsValues: "SetInterventionsValues",
    SetInvestmentValues: "SetInvestmentValues",
    SetReadinessValues: "SetReadinessValues",
    SetStakeholdersValues: "SetStakeholdersValues",

}